pub mod document;
pub mod editor;
pub mod file_monitor;
pub mod recovery;
pub mod line_ops;
pub mod column_ops;
pub mod bookmarks;
pub mod folding;
pub mod document_map;
pub mod split_view;

pub use document::{Document, DocumentError, Encoding, LegacyEncoding, LineEnding};
pub use editor::{Caret, EditorBuffer, EditorError, Selection};
pub use file_monitor::{FileEvent, FileMonitor, FileMonitorError, FileMonitorEventKind};
pub use recovery::{RecoveryEntry, RecoveryManager};
pub use line_ops::{CaseTransform, SortOrder};
pub use column_ops::ColumnSelection;
pub use bookmarks::BookmarkManager;
pub use folding::{FoldRegion, FoldTree};
pub use document_map::{DocumentMapEntry, DocumentMetrics};
pub use split_view::{MultiInstancePolicy, Pane, SplitViewState, TabId, TabRecord};
